# Collection of adverbs
# September 19 2014
# Christian Bauer

d = { }
drev = { }
num = 0

def ins(x):
    global num,d,drev
    d[num] = x
    drev[x] = num
    num = num + 1

ins('accidentally')
ins('always')
ins('angrily')
ins('anxiously')
ins('awkwardly')
ins('badly')
ins('blindly')
ins('boastfully')
ins('boldly')
ins('bravely')
ins('brightly')
ins('cheerfully')
ins('coyly')
ins('crazily')
ins('defiantly')
ins('deftly')
ins('deliberately')
ins('devotedly')
ins('doubtfully')
ins('dramatically')
ins('dutifully')
ins('eagerly')
ins('elegantly')
ins('enormously')
ins('evenly')
ins('eventually')
ins('exactly')
ins('faithfully')
ins('finally')
ins('foolishly')
ins('fortunately')
ins('frantically')
ins('frequently')
ins('gleefully')
ins('gracefully')
ins('happily')
ins('hastily')
ins('honestly')
ins('hopelessly')
ins('hourly')
ins('hungrily')
ins('innocently')
ins('inquisitively')
ins('irritably')
ins('jealously')
ins('justly')
ins('kindly')
ins('lazily')
ins('loosely')
ins('madly')
ins('merrily')
ins('mortally')
ins('mysteriously')
ins('nervously')
ins('never')
ins('obediently')
ins('obnoxiously')
ins('occasionally')
ins('often')
ins('only')
ins('perfectly')
ins('politely')
ins('poorly')
ins('powerfully')
ins('promptly')
ins('quickly')
ins('rapidly')
ins('rarely')
ins('really')
ins('regularly')
ins('rudely')
ins('safely')
ins('seldom')
ins('selfishly')
ins('seriously')
ins('shakily')
ins('sharply')
ins('silently')
ins('slowly')
ins('solemnly')
ins('sometimes')
ins('speedily')
ins('steadily')
ins('sternly')
ins('technically')
ins('tediously')
ins('tenderly')
ins('terrifically')
ins('tightly')
ins('totally')
ins('tremendously')
ins('unexpectedly')
ins('usually')
ins('victoriously')
ins('vivaciously')
ins('warmly')
ins('wearily')
ins('weekly')
ins('wildly')
ins('yearly')
